services:
  mysql:
    image: mariadb:10.4
    container_name: msqlchamo_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/mysql.cnf:/etc/mysql/conf.d/replication.cnf:ro
    networks:
      - db_network

  postgresql:
    image: postgres:17
    container_name: msqlchamo_postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby=on
      -c max_logical_replication_workers=4
      -c max_worker_processes=10
    networks:
      - db_network

volumes:
  mysql_data:
  postgresql_data:

networks:
  db_network:
    driver: bridge
